### ISSUE TITLE
 Fatal error: Call to a member function get() on null

### ISSUE THREAD

**Issue by cosmomathieu** [avramovic/DMLite-ORM#2]
Hi, thank you for putting up this project. But I have the following error `Fatal error: Call to a member function get() on null` at this line `$this->groups->get();`. Does the group->get() option exist still?

**Comment by avramovic** [comment]
Hello there,

Thank you for using this library. It seems `$this->groups` is **null**. You shouldn't be using DML models as CI models - you need to make new instances manually, so:

```
$groups = new Group(); //you should really name your model classes as singular, i.e. Group
$groups->get();
```

or:

`$groups = Group::factory()->get();`

or, to fetch single group:

```
$group_id = 1;
$group = Group::factory($group_id);
// or:
$group = new Group();
$group->where('id', $group_id)->limit(1)->get();
// or:
$group = Group::factory()->get_by('id', $group_id);
// or:
$group = Group::factory()->get_by_id($group_id);
```

You can use any of these method calls to achieve the same result.

edit: Make sure you have loaded your models before using them :)

**Comment by cosmomathieu** [comment]
OK, I'll try the methods mentioned above. I'll let you know.
