### ISSUE TITLE
Error: wrong formed query in include related

### ISSUE THREAD

**Issue by danonunez** [avramovic/DMLite-ORM#3]
Hi avramovic, thanks for sharing your project.

There is an error when performing a query with a related table as "has_many". the query creates 2 "JOIN" to the same table, when in fact they should be only 1 "JOIN" and 2 clauses "ON".
# 

Error Number: 1066

Not unique table/alias: 'usuario'

SELECT `restriccion`.\* FROM `restriccion` JOIN `usuario` ON `usuario`.`rol_id` = `rol`.`id` JOIN `usuario` ON `usuario`.`id` = `restriccion`.`usuario_id` WHERE usuario.`id` = ? AND usuario.`id` = ?

Filename: core/MY_Model.php
# Line Number: 367

**Comment by avramovic** [comment]
Whoops, I have no idea how I missed this. If this is still bothering you, can you please post your (user) code which is causing this issue? I'm not actually developing this anymore (switched to Laravel and its awesome Eloquent) but I would try to fix it for the others.

**Comment by danonunez** [comment]
Sorry, i'm not currently working with this, i used in my previous job so I no longer have the code.
Regards
