### ISSUE TITLE
It's not an issue - rather question or request.

### ISSUE THREAD

**Issue by rtofvnt** [avramovic/DMLite-ORM#6]
Hi
I'm working on little project and I found this  DMLite-ORM very useful. 
On every day job I'm dealing with CI2.0 with DataMapper by WanWizzard and there is one thing that is implemented (I don't know if by WanWizzard or developer of this project) that is quite good.
When I create new object and provide id it creates instantly object without calling get() function:
$country = New Country(253);
where in DMLite-ORM I need to do something like:
$country = New Country():
$country->where('id',253)->get();

Am I missing something here ? 
Cheers - Matt.

**Comment by avramovic** [comment]
Hi,

You can use `Country::factory(253);` to automatically get row with ID 253

**Comment by rtofvnt** [comment]
Thanks - it makes perfect sense and also helps me improve my understanding of OOP paradigm.
Cheers
