### ISSUE TITLE
include_related doesn't seems to be working 

### ISSUE THREAD

**Issue by rtofvnt** [avramovic/DMLite-ORM#7]
Hi,
It's probably me missing something obvious. I have:
`$user = New User();
        $user->where('email',$email);
        $user->include_related('company');
        $user->get();`
I'm getting that:
Severity: User Notice
Message: Unable to relate User with Company!

having in users table column company_id 
and relations in models:
User has one 'company' and in Companies has many ('users','addresses').
You wouldn't mind to light up my journey with this problem ? 
Thanks - Matt.

**Comment by avramovic** [comment]
Can you show your tables' structure as well as class files (only `$has_one` and `$has_many` relations are important)?

**Comment by rtofvnt** [comment]
Hi,
This is 'users' table:
   id  email                      company_id  created              updated  status  
   9  xxx@gmail.com                       6   (NULL)               (NULL)            1

and this is 'companies' table:
    id  name                    type  country_id  postcode_id  status  created  updated  
     1  Company A               1             225                670         1  (NULL)   (NULL)   

This is from User model;

```
Class User extends MY_Model {
    public $has_one = array('company');

```

This comes from Company model:

```
class Company extends MY_Model {
    public $has_many = array('address','user','transport_types');
```

Then in controller for example:

```
$test_user = New User();
$test_user->where('id',9);
$test_user->include_related('company');
$test_user->get();
echo $test_user->company->name;

```

however as I'm typing this and checked couple of things I think I'm getting there.
Initially I didn't have in companies table created and updated columns, but I don't think this was a problem. 
Another thing I've noticed when I turn last line to:
`echo $test_user->company_name;`
I can see 'company name'. 
Am I doing this right ? 

Thanks - Matt.

**Comment by avramovic** [comment]
I think you're doing it right. Note that related models are not initialized - you have no object at `$test_user->company`, but you have the data (`$test_user->company_name`)

**Comment by rtofvnt** [comment]
Ok - cool.
Does that mean I have to do every time:

```
  $test_user->include_related('company');
  $test_user->get();
  $test_user->company->get();
```

to have test_user->company object ?
Cheers

**Comment by avramovic** [comment]
No, you can't do that because `$test_user->company` doesn't exist. If you need an object, you already have it's ID so you can fetch it easily without using `include_related()`:

`$test_user->company = Company::factory($test_user->company_id);`

I can easily make a new method (e.g. `$test_user->init_related('company')`) using similar code, or even hook it up to work seamlessly with `include_related()`, but it's using another database query to load that object, and the main idea behind `include_related()` is to load related model data in a single query.

What I need to do is initialize related model with the `company_*` data returned by using `include_related()` but without making additional queries to the database. Give me a couple of days and I'll figure it out.

**Comment by rtofvnt** [comment]
That would be brilliant,  however I think I can get used to ::factory function and carry on using this. 
Thanks a million for looking at this.
Cheers

**Comment by avramovic** [comment]
You can get used to it, but imagine having 10000 users and you want to display name of (or do something else with) their company...

```
$users = User::factory()->get();
foreach ($users as $user) {
  $user->company = Company::factory($user->company_id);
  // do something with $user->company
}
```

This code would produce [10001 queries](http://stackoverflow.com/questions/97197/what-is-the-n1-selects-issue) and it'd most likely kill your db server. Therefore the way I described above is the correct way to solve this issue :)

**Comment by rtofvnt** [comment]
You right :-)
Cool - I'll look forward for your solution and meanwhile I have other
things to sort in this project.
Best Regards - Matt.

2016-10-31 23:24 GMT+00:00 Nemanja Avramović notifications@github.com:

**Comment by avramovic** [comment]
OK, use the latest version and try something like this:

```
$test_user = New User();
$test_user->where('id',9);
$test_user->include_related('company', true); //note the TRUE param here
$test_user->get();
echo $test_user->company->name;`
```

This should work both for `$has_one` and `$has_many` relationships (produces ONE additional query for `$has_many` relationships). It doesn't work on deep relationships though (e.g. `$test_user->include_related('company/products', true);`)

**Comment by rtofvnt** [comment]
That's it. It works like a charm.
Thank you very much. 
In my everyday job I'm working on some project built in CI2.0 with wanwizzard datamapper and we had to rewrite quite a few lines to drop usage of deep relationships as it was generating giant sql queries, so your solution for my project is perfect.
Thanks again.
